server:
  port: 8082

spring:
  application:
    name: sltourguiderestapi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SLTourGuide
    username: postgres
    password: 199249

